#!/usr/bin/env python
import rospy


def wait_for_services():
    if not rospy.wait_for_service("/controller_manager/switch_controller", 30):
        rospy.logerr("failed to get service")
        exit(1)


if __name__ == "__main__":
    rospy.init_node("arm_science_node")
    wait_for_services()